[colors.primary]
foreground = "#775566"
background = "#ffffff"

[colors.cursor]
text = "#ffffff"
cursor = "#775566"

[colors.selection]
text = "#775566"
background = "#eeddee"

[colors.normal]
black   = "#775566"
red     = "#aa77aa"
green   = "#bb99cc"
yellow  = "#eeddee"
blue    = "#aa99cc"
magenta = "#ddbbdd"
cyan    = "#ccbbdd"
white   = "#faf2fa"

[colors.bright]
black   = "#775566"
red     = "#aa77aa"
green   = "#bb99cc"
yellow  = "#eeddee"
blue    = "#aa99cc"
magenta = "#ddbbdd"
cyan    = "#ccbbdd"
white   = "#faf2fa"
