[colors.cursor]
text = "#ffffff"
cursor = "#aa0000"

[colors.primary]
foreground = "#aa0000"
background = "#ffffdd"

[colors.normal]
black   = "#aa0000"
red     = "#aa0000"
green   = "#ee8888"
yellow  = "#ffcccc"
blue    = "#ffaaaa"
magenta = "#ffaaaa"
cyan    = "#ffaaaa"
white   = "#ffffff"

[colors.bright]
black   = "#aa0000"
red     = "#aa0000"
green   = "#ee8888"
yellow  = "#ffcccc"
blue    = "#ffaaaa"
magenta = "#ffaaaa"
cyan    = "#ffaaaa"
white   = "#ffffff"
