#! /usr/bin/env bash

black='\033[0;100m'
red='\033[0;101m'
yellow='\033[0;102m'
green='\033[0;103m'
blue='\033[0;104m'
magenta='\033[0;105m'
cyan='\033[0;106m'
white='\033[0;107m'

echo -e "$black   $red   $yellow   $green   $blue   $magenta   $cyan   $white   "
