#! /usr/bin/env bash

# dependencies: maim

IMGDIR=$HOME/Pictures/screenshot
Q=10

mkdir -p $HOME/Pictures
mkdir -p $IMGDIR

name=$(date "+%Y%m%d_%H%M%S.png")

case "$1" in
    "-s" )
        maim -u -m $Q -s $IMGDIR/$name
        ;;
    "-f" )
        maim -u -m $Q $IMGDIR/$name
        ;;
esac
