import = ["~/.config/alacritty/colors/github_dark_tritanopia.toml"]

[font]
size = 12

[window]
opacity = 1.0
dynamic_title = true

[window.padding]
x = 8
y = 8

[window.dimensions]
lines = 26
columns = 86

[scrolling]
history = 4096

[cursor.style]
shape = "block"

[font.normal]
family = "NotoSansMono"

[font.bold]
family = "NotoSansMono"

[font.italic]
family = "NotoSansMono"
