[general]
import = [ "~/.config/alacritty/themes/current" ]
live_config_reload = true

[window]
dimensions = { columns = 96, lines = 32 }
padding = { x = 0, y = 0 }
dynamic_title = true

[scrolling]
history = 10000

[font]
normal = { family = "JetBrainsMono", style = "Regular" }
bold = { family = "JetBrainsMono", style = "Bold" }
italic = { family = "JetBrainsMono", style = "Italic" }
size = 9

[cursor]
# shape = Block | Beam
style = { shape = "Block", blinking = "Always" }

