theme = "github_dark"

[editor]
shell = ["bash", "-c"]
line-number = "absolute"
cursorline = true
cursorcolumn = false
auto-save = true
bufferline = "multiple"

[editor.statusline]
left = ["mode"]
center = []
right = ["position", "position-percentage", "spacer", "file-base-name", "file-encoding"]

mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.whitespace.render]
space = "all"
tab = "all"
nbsp = "none"
nnbsp = "none"
newline = "none"

[editor.whitespace.characters]
space = "·"
tab = "→"
tabpad = "·"
nbsp = "⍽"
nnbsp = "␣"
newline = "⏎"

[editor.indent-guides]
render = true
character = "╎"

[keys.normal]
r = "redo"

"C-h" = "jump_view_left"
"C-j" = "jump_view_down"
"C-k" = "jump_view_up"
"C-l" = "jump_view_right"
